import type { Config } from "tailwindcss"
import animate from "tailwindcss-animate"

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#faf8fe",
        "surface-dim": "#dad9df",
        "surface-bright": "#faf8fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f8",
        "surface-container": "#eeedf3",
        "surface-container-high": "#e9e7ed",
        "surface-container-highest": "#e3e2e7",
        "on-surface": "#1a1b1f",
        "on-surface-variant": "#4c4546",
        "inverse-surface": "#2f3034",
        "inverse-on-surface": "#f1f0f5",
        "outline": "#7e7576",
        "outline-variant": "#cfc4c5",
        "surface-tint": "#5e5e5e",
        "primary": "#000000",
        "on-primary": "#ffffff",
        "primary-container": "#1b1b1b",
        "on-primary-container": "#848484",
        "inverse-primary": "#c6c6c6",
        "secondary": "#5d5e60",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfdfe1",
        "on-secondary-container": "#616365",
        "tertiary": "#000000",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#001b3f",
        "on-tertiary-container": "#2b82f4",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#e2e2e2",
        "primary-fixed-dim": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-primary-fixed-variant": "#474747",
        "secondary-fixed": "#e2e2e4",
        "secondary-fixed-dim": "#c6c6c8",
        "on-secondary-fixed": "#1a1c1d",
        "on-secondary-fixed-variant": "#454749",
        "tertiary-fixed": "#d7e2ff",
        "tertiary-fixed-dim": "#abc7ff",
        "on-tertiary-fixed": "#001b3f",
        "on-tertiary-fixed-variant": "#00458f",
        "background": "#faf8fe",
        "on-background": "#1a1b1f",
        "surface-variant": "#e3e2e7",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
        card: "32px",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        xxl: "120px",
        "container-max": "1440px",
        gutter: "32px",
        "margin-mobile": "20px",
      },
      maxWidth: {
        "container-max": "1440px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "display-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "display-sm": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [animate],
}

export default config
